[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#87f5d3"
backgroundColor = "#040914"
secondaryBackgroundColor = "#0b1526"
textColor = "#f4f8ff"
font = "sans serif"
